In [24]:
import numpy as np

#### Create array , matrix

In [25]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [26]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [27]:
# shape 
print(a.shape,b.shape)

(4,) (2, 2)


In [12]:
# reshape 
c=a.reshape((4,1))
c.shape

(4, 1)

In [28]:
d = a.reshape((2,2,1))
d

array([[[1],
        [2]],

       [[3],
        [4]]])

In [16]:
# conctenate 

a= np.array([1,2,3])
b = np.array([4,5])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a * b
c

array([ 4, 10, 18])

In [31]:
c = np.array([10])
d = a + c
d

array([11, 12, 13])

In [30]:
e = a + 5
e

array([6, 7, 8])

In [29]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape

(9,)

In [35]:
b = a[2:7:2]
b

array([3, 5, 7])

In [37]:
c= a[a>3]
c

array([4, 5, 6, 7, 8, 9])

In [38]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
sum_a= np.sum(a)
sum_a

45

In [44]:
max_a = np.max(a)
max_a

9

In [45]:
min_a = np.min(a)
min_a

1

In [30]:
a = np.array([4,2,9,6,7,3,5])
b = np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 9])

In [31]:
a = np.random.randint(0,10,(3,4))
a

array([[5, 9, 4, 3],
       [8, 0, 1, 9],
       [8, 5, 4, 6]])

In [32]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a , b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
e = np.hstack((a , b))
e

array([1, 2, 3, 4, 5, 6])

In [36]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [37]:
# normalize
mean_a = np.mean(a)
mean_a

3.5

In [38]:
std_a=np.std(a)
std_a

1.707825127659933

In [39]:
norm_a = (a - mean_a)/std_a
norm_a

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [40]:
np.mean(norm_a)

-3.700743415417188e-17

In [41]:
np.std(norm_a)

1.0