In [256]:
import tensorflow as tf

print(tf.__version__)

2.15.0


In [257]:
print(tf.test.gpu_device_name())

/device:GPU:0


In [258]:
a = tf.constant(5)
a


<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [259]:
c=tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
c

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [260]:
b=tf.constant([1,2,3,4])
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# different opperation

In [261]:
a = tf.constant([1,2])
b = tf.constant([3,4])

In [262]:
# sum
c=tf.add(a,b)
c.numpy()

array([4, 6], dtype=int32)

In [263]:
# subtract
d = tf.subtract(a,b)
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [264]:
# multiplication
a_1 = tf.constant([[1,2],[3,4]])
b_1 = tf.constant([[0,1],[2,3]])

In [265]:
ew= tf.multiply(a_1,b_1)
ew

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0,  2],
       [ 6, 12]], dtype=int32)>

In [266]:
mm = tf.matmul(a_1,b_1)
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  7],
       [ 8, 15]], dtype=int32)>

In [267]:
# division
a = tf.constant([1,2]) #1,2
b = tf.constant([3,4]) #3,4


In [268]:
d = tf.divide(a,b)
d

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.33333333, 0.5       ])>

In [269]:
# Broadcasting

a = tf.constant([1,2,3])
b = tf.constant(4) # => a * [4,4,4]

c = a * b # => + - *

c


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12], dtype=int32)>

## Reshape

In [270]:
# Reshape
a = tf.constant([1,2,3,4,5,6])
a.shape
a


TensorShape([6])

In [271]:
b = tf.reshape(a, shape=(3,2,1))
b.shape

TensorShape([3, 2, 1])

In [272]:
b

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [273]:
#add dimension
a = tf.constant([1,2,3,4,5,6])
a.shape

TensorShape([6])

In [274]:
b = tf.expand_dims(a,-1)
b.shape

TensorShape([6, 1])

In [275]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [276]:
b

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [277]:
a = tf.constant([[1,2],[3,4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [278]:
b = tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [279]:
c = tf.sqrt(tf.cast(a , dtype=float))
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [1.7320508, 2.       ]], dtype=float32)>

## Min , Max , Mean ,STD

In [280]:
a = tf.constant([[1,2],[3,4]], dtype = tf.float32)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [281]:
min = tf.reduce_min(a,axis=1)
min.numpy()

array([1., 3.], dtype=float32)

In [282]:
max = tf.reduce_max(a,axis=1)
max.numpy()

array([2., 4.], dtype=float32)

In [283]:
# numpy
import numpy as np
a = np.array([[1,2],[3,4]])
a.mean()

2.5

In [284]:
avg = tf.reduce_mean(a)
avg.numpy()

2

In [285]:
sum = tf.reduce_sum(a)
sum.numpy()

10

In [286]:
E = tf.cast(a, dtype=tf.float32)
std = tf.math.reduce_std(E)
std.numpy()

1.1180339